code/Avtoservis/routes/web.php
<?php
use Symfony\Component\HttpKernel\Fragment\RoutableFragmentRenderer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/index', function() {
    return view('index');
})->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('cars', 'CarsController');
Route::resource('reservations', 'ReservationsController');



// Route::get('/projects', 'ProjectsController@index');
// Route::get('/projects/create', 'ProjectsController@create');
// Route::get('/projects/{id}', 'ProjectsController@show');
// Route::post('/projects', 'ProjectsController@store');
// Route::get('/projects/{id}/edit', 'ProjectsController@edit');
// Route::patch('/projects/{id}', 'ProjectsController@update');
// Route::delete('/projects/{id}', 'ProjectsController@destroy');

code/Avtoservis/resources/views/partial/footer.blade.php
<footer class="py-4 bg-light text-dark text-center">
    <div class="container">
        {{ date("Y") }} &copy; Mitja Hrovatič
    </div>
</footer>

code/Avtoservis/resources/views/partial/navbar-index-page.blade.php
<nav class="navbar fixed-top navbar-expand-md navbar-dark  bg-primary shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link smooth_scroll" href="#top">{{ __('Domov') }}</a>
                    </li>
                    {{-- <li class="nav-item">
                        <a class="nav-link smooth_scroll" href="#o-nas">{{ __('O nas') }}</a>
                    </li> --}}
                    <li class="nav-item">
                        <a class="nav-link smooth_scroll" href="#kontakt">{{ __('Kontakt') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('reservations.create') }}">{{ __('Naročilo na servis') }}</a>
                    </li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        {{-- <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Prijava') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Registracija') }}</a>
                            </li>
                        @endif --}}
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} {{ Auth::user()->lastname }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('home') }}">
                                    {{ __('Nadzorna plošča') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('cars.create') }}">
                                    {{ __('Dodaj avtomobil') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('reservations.create') }}">
                                    {{ __('Noroči se na servis') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Odjava') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

code/Avtoservis/resources/views/partial/navbar.blade.php
<nav class="navbar fixed-top navbar-expand-md navbar-dark  bg-primary shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('index') }}">{{ __('Domov') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">{{ __('Nadzorna plošča') }}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('reservations.create') }}">{{ __('Naročilo na servis') }}</a>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Prijava') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Registracija') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} {{ Auth::user()->lastname }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('home') }}">
                                     {{ __('Nadzorna plošča') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('cars.create') }}">
                                     {{ __('Dodaj avtomobil') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('reservations.create') }}">
                                     {{ __('Noroči se na servis') }}
                                </a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                    {{ __('Odjava') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

<div class="margin-top-navbar"></div>

code/Avtoservis/resources/views/partial/reservation-table.blade.php
<div class="container mt-5" id="width_change">
    <div class="jumbotron-fluid rounded-20 bg-white pb-2">
        <div class="table-responsive">
            <table class="table table-hover" id="dataTableForExcel">
                <thead>
                    <tr>
                        <th scope="col">Inventarna</th>
                        <th scope="col">Oddelek</th>
                        <th scope="col">Uporabnik</th>
                        <th scope="col">Ime rač.</th>
                        <th scope="col">Naziv</th>
                        <th scope="col">Datum spremembe na IT</th>
                        <th scope="col">Izvajalec</th>
                        <th scope="col">Opis problema</th>
                        <th scope="col">Opis posega</th>
                        <th scope="col" class="hiddenCol">
                            <button type="button" id="viewPort" class="btn btn-primary btn-sm topBarCreate ml-lg-4" data-tippy="Širina">
                                <i class="material-icons">code</i>
                            </button>
                        </th>
                    </tr>
                </thead>
                <tbody>
                        <tr>
                            <td scope="row">asdfasd</td>
                            <td>asdfasd</td>
                            <td>asdfasd</td>
                            <td>asdfasd</td>
                            <td>asdfasd</td>
                            <td>asdfasd</td>
                            <td>asdfasd</td>
                            <td>asdfasd</td>
                            <td>asdfasd</td>
                                <td width="150" class="hiddenCol">
                                    <div class="d-inline-block uporavljanje_posega">
                                        <button type="button" class="btn btn-warning topBarCreate my-1 my-lg-0 poseg_edit_@item.Poseg_ID" data-toggle="modal" data-target=".crud_form_modal_poseg_@item.Poseg_ID" data-tippy="Uredi">
                                            <i class="material-icons">edit</i>
                                        </button>
                                        {{-- @if (Model._Prijavljen_Uporabnik.Pravice.Koda_pravice == "ADMIN")
                                        {
                                            <button type="button" class="btn btn-danger topBarCreate my-1 my-lg-0" data-toggle="modal" data-target=".delet_poseg_@item.Poseg_ID" data-tippy="Zbriši">
                                                <i class="material-icons">delete</i>
                                            </button>
                                        } --}}
                                    </div>

                                    <div class="modal fade bd-example-modal-lg crud_form_modal_poseg_@item.Poseg_ID" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
                                        <div class="modal-dialog modal-dialog-centered modal-dialog modal-lg" role="document">
                                            asdf
                                        </div>
                                    </div>



                                    {{-- @if (Model._Prijavljen_Uporabnik.Pravice.Koda_pravice == "ADMIN")
                                    {
                                        <!-- Small modal -->
                                        <div class="modal fade delet_poseg_@item.Poseg_ID" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
                                            <div class="modal-dialog modal-dialog-centered modal-dialog modal-sm" role="document">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <h5 class="modal-title" id="exampleModalLongTitle">Odstrani poseg</h5>
                                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                            <span aria-hidden="true">&times;</span>
                                                        </button>
                                                    </div>
                                                    <div class="modal-body">
                                                        Želite izbrisati poseg
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Prekliči</button>
                                                        @using (Html.BeginForm("Delete", "Poseg", new { ReturnUrl = ViewBag.ReturnUrl, id = item.Poseg_ID }, FormMethod.Post, new { role = "form" }))
                                                        {
                                                            @Html.AntiForgeryToken()
                                                            <input type="submit" class="btn btn-primary" value="Potrdi" />
                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    } --}}
                                </td>
                        </tr>
                </tbody>
            </table>
        </div>


        {{-- @*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount*@

        <div class="ml-3 mt-2">
            @Html.PagedListPager(Model._Posegi_List, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
        </div> --}}
    </div>
</div>