code/Avtoservis/routes/web.php
<?php
use Symfony\Component\HttpKernel\Fragment\RoutableFragmentRenderer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/index', function() {
    return view('index');
})->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('cars', 'CarsController');
Route::resource('reservations', 'ReservationsController');



// Route::get('/projects', 'ProjectsController@index');
// Route::get('/projects/create', 'ProjectsController@create');
// Route::get('/projects/{id}', 'ProjectsController@show');
// Route::post('/projects', 'ProjectsController@store');
// Route::get('/projects/{id}/edit', 'ProjectsController@edit');
// Route::patch('/projects/{id}', 'ProjectsController@update');
// Route::delete('/projects/{id}', 'ProjectsController@destroy');

code/Avtoservis/app/Reservation.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Reservation extends Model
{
    protected $primaryKey = 'id_rezervacije';

    protected $fillable = [
        'id_uporabnika',
        'id_storitve',
        'id_avtoservis',
        'id_avtomobila',
        'termin',
        'dodatni_opis',
        'is_confirm'
    ];
}

code/Avtoservis/app/Http/Controllers/ReservationsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;
use App\Reservation;
use App\Car;
use App\Avtoservi;
use App\Service;

class ReservationsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $reservations = Reservation::where('id_uporabnika', auth()->id())->orderBy('termin', 'desc')->paginate(4);

        return response()->json($reservations);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cars = Car::where('id_uporabnika', auth()->id())->get();
        $avtoservis = Avtoservi::get();
        $services = Service::get();
        return view('reservation.create', compact('cars', 'avtoservis', 'services'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'id_uporabnika' => 'required|integer',
            'id_storitve' => 'required|integer',
            'id_avtoservis' => 'required|integer',
            'id_avtomobila' => 'required|integer',
            'termin' => 'required', // |regex:/(\d{4})\-(\d{2})\-(\d{2}) (\d{2})\:(\d{2})\:(\d{2})/
            'dodatni_opis' => 'required',
            'is_confirm' => 'required'
        ]);

        $car = Reservation::create($data);

        return redirect('/home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function messages()
    {
        return [
            'termin.required' => 'Termin je obvezen',
            'dodatni_opis.required'  => 'Dodatni opis je obvezen',
        ];
    }
}

code/Avtoservis/resources/views/reservation/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="jumbotron text-center login_form shadow-lg p-3 my-5 bg-white">
                <div class="title m-b-md">
                    Naroči se na servis
                </div>
                <div>
                    <form action="{{ route('reservations.store') }}" method="post">
                        @csrf

                        <input type="hidden" name="id_uporabnika" value="{{ auth()->id() }}">
                        <input type="hidden" name="is_confirm" value="0">

                        {{-- @if($errors->any())
                            <div class="errors">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif --}}

                        <div class="form-group form-id_storitve">
                            <select class="form-control @error('id_storitve') is-invalid @enderror" id="id_storitve" name="id_storitve" oninput="id_storitveValidacija()">
                                <option value="">Izberite storitev</option>
                                @foreach ($services as $service)
                                    <option value="{{ $service->id_storitve }}">{{ $service->naziv }}</option>
                                @endforeach
                            </select>

                            @error('id_storitve')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group form-id_avtoservis">
                            <select class="form-control @error('id_avtoservis') is-invalid @enderror" id="id_avtoservis" name="id_avtoservis" oninput="id_avtoservisValidacija()">
                                    <option value="">Izberite avtoservis</option>
                                @foreach ($avtoservis as $avts)
                                    <option value="{{ $avts->id_avtoservis }}">{{ $avts->poslovalnica }}</option>
                                @endforeach
                            </select>

                            @error('id_avtoservis')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group form-id_avtomobila">
                            <select class="form-control @error('id_avtomobila') is-invalid @enderror" id="id_avtomobila" name="id_avtomobila" oninput="id_avtomobilaValidacija()">
                                    <option value="">Izberite avtomobil</option>
                                @foreach ($cars as $car)
                                    <option value="{{ $car->id_avtomobila }}">{{ $car->znamka }} {{ $car->model }}</option>
                                @endforeach
                            </select>

                            @error('id_avtomobila')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group form-termin">
                            <input type="datetime-local" class="form-control @error('termin') is-invalid @enderror" name="termin" id="termin" placeholder="Termin - yyyy-mm-dd hh:mm" value="{{ old('termin') }}" oninput="terminValidacija()">

                            @error('termin')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group form-dodatni_opis">
                            <textarea name="dodatni_opis" class="form-control @error('dodatni_opis') is-invalid @enderror" id="dodatni_opis" placeholder="Dodatni opis napak" cols="15" rows="5" oninput="dodatni_opisValidacija()">{{ old('dodatni_opis') }}</textarea>

                            @error('dodatni_opis')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary btn-padding" value="Naroči">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

code/Avtoservis/resources/views/reservation/index.blade.php
@extends('layouts.app')

@section('content')


    <div class="title m-b-md">
        Seznam Cars
    </div>
    <a href="/cars/create">Dodaj avtomobil</a>

    <div>
        <table>

            @foreach($cars as $car)
                <tr>
                    <td>{{ $car->znamka }}</td>
                    <td>{{ $car->model }}</td>
                    <td>{{ $car->letnik }}</td>
                    <td>{{ $car->opis }}</td>
                    <td><a href="/cars/{{ $car->id }}">Podrobnosti</a></td>
                    <td><a href="/cars/{{ $car->id }}/edit">Uredi</a></td>
                    <td>
                        <form action="/cars/{{ $car->id }}" method="POST">
                            @csrf
                            @method('DELETE')

                            <button type="submit">Izbriši</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>

@endsection

code/Avtoservis/resources/views/reservation/show.blade.php
@extends('layouts.app')

@section('content')

<div class="title m-b-md">
    {{ $car->znamka }} {{ $car->model }}
</div>

<div class="content">
    <ul>
        <li>{{ $car->letnik }}</li>
        <li>{{ $car->opis }}</li>
    </ul>
</div>

@endsection

code/Avtoservis/resources/views/reservation/update.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="jumbotron text-center login_form shadow-lg p-3 my-5 bg-white">
                <div class="title m-b-md">
                    Uredi avtomobil
                </div>
                <div>
                    <form action="/cars/{{ $car->id }}" method="post">
                        @method('PATCH')
                        @csrf

                        <div class="form-group">
                            <label for="znamka">Znamka avtomobila</label>
                            <input type="text" class="form-control" name="znamka" id="znamka" value="{{ $car->znamka }}">
                        </div>
                        <div class="form-group">
                            <label for="model">Model avtomobila</label>
                            <input type="text" class="form-control" name="model" id="model" value="{{ $car->model }}">
                        </div>
                        <div class="form-group">
                            <label for="letnik">Leto izdelave</label>
                            <input type="text" class="form-control" name="letnik" id="letnik" value="{{ $car->letnik }}">
                        </div>
                        <div class="form-group">
                            <label for="opis">Opis avtomobila</label>
                            <textarea name="opis" class="form-control" id="opis" cols="30" rows="10">{{ $car->opis }}</textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Popravi">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection