code/Avtoservis/routes/web.php
<?php
use Symfony\Component\HttpKernel\Fragment\RoutableFragmentRenderer;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/index', function() {
    return view('index');
})->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('cars', 'CarsController');
Route::resource('reservations', 'ReservationsController');



// Route::get('/projects', 'ProjectsController@index');
// Route::get('/projects/create', 'ProjectsController@create');
// Route::get('/projects/{id}', 'ProjectsController@show');
// Route::post('/projects', 'ProjectsController@store');
// Route::get('/projects/{id}/edit', 'ProjectsController@edit');
// Route::patch('/projects/{id}', 'ProjectsController@update');
// Route::delete('/projects/{id}', 'ProjectsController@destroy');

code/Avtoservis/app/Car.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model
{
    protected $primaryKey = 'id_avtomobila';

    protected $fillable = [
        'id_uporabnika',
        'znamka',
        'model',
        'leto_prve_registracije',
        'opis',
        'is_active'
    ];
}

code/Avtoservis/app/Http/Controllers/CarsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Http\Request;
use App\Car;
use Illuminate\Database\Eloquent\Builder;

class CarsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cars = Car::where('id_uporabnika', auth()->id())->get();

        return response()->json($cars);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('car.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


        $data = $request->validate([
            'id_uporabnika' => 'required|integer',
            'znamka' => 'required',
            'model' => 'required',
            'leto_prve_registracije' => 'required|integer|regex:/^(\d{4})$/',
            'opis' => 'required',
            'is_active' => 'required|integer|between:0,1'
        ]);

        $car = Car::create($data);

        // [
        //     'id_uporabnika' => auth()->id(),
        //     'znamka' => $request->znamka,
        //     'model' => $request->model,
        //     'leto_prve_registracije' => $request->letnik,
        //     'opis' => $request->opis,
        //     'is_active' => 1
        // ]

        return redirect('/home');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $car = Car::where("id_avtomobila", $id)->first();
        return response()->json($car);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $car = Car::where("id_avtomobila", $id)->first();
        return view('car.update', compact('car'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'id_uporabnika' => 'required|integer',
            'znamka' => 'required',
            'model' => 'required',
            'leto_prve_registracije' => 'required|integer|regex:/(\d{4})/',
            'opis' => 'required',
            'is_active' => 'required|integer|between:0,1'
        ]);

        $car = Car::where("id_avtomobila", $id)->first();
        $car->id_uporabnika = $request->get('id_uporabnika');
        $car->znamka = $request->get('znamka');
        $car->model = $request->get('model');
        $car->leto_prve_registracije = $request->get('leto_prve_registracije');
        $car->opis = $request->get('opis');
        $car->is_active = $request->get('is_active');
        $car->save();

        return redirect('/home');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Schema::disableForeignKeyConstraints();
        $car = Car::where("id_avtomobila", $id)->delete();

        // if ($car){
        //     $data = [
        //         'message' => 'Uspešno ste izbrisali avtomobil'
        //     ];
        // } else {
        //     $data = [
        //         'message' => 'Brisanje ni bilo uspešno'
        //     ];
        // }
        return response()->json([
            'message' => 'Uspešno ste izbrisali avtomobil'
        ]);
    }
}

code/Avtoservis/resources/views/car/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="jumbotron text-center login_form shadow-lg p-3 my-5 bg-white">
                <div class="title m-b-md">
                    Dodaj avtomobil
                </div>
                <div>
                    <form action="{{ route('cars.store') }}" method="post">
                        @csrf

                        <input type="hidden" name="id_uporabnika" value="{{ auth()->id() }}">
                        <input type="hidden" name="is_active" value="1">

                        {{-- @if($errors->any())
                            <div class="errors">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif --}}

                        <div class="form-group form-znamka">
                            <input type="text" class="form-control @error('znamka') is-invalid @enderror" name="znamka" id="znamka" placeholder="Znamka avtomobila" value="{{ old('znamka') }}" oninput="znamkaValidacija()" autofocus>

                            @error('znamka')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group form-model">
                            <input type="text" class="form-control @error('model') is-invalid @enderror" name="model" id="model" placeholder="Model avtomobila" value="{{ old('model') }}" oninput="modelValidacija()">

                            @error('model')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group form-leto_prve_registracije">
                            <input type="number" class="form-control @error('leto_prve_registracije') is-invalid @enderror" name="leto_prve_registracije" id="leto_prve_registracije" placeholder="Leto izdelave" value="{{ old('leto_prve_registracije') }}" oninput="leto_prve_registracijeValidacija()">

                            @error('leto_prve_registracije')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group form-opis">
                            <textarea name="opis" class="form-control @error('opis') is-invalid @enderror" id="opis" placeholder="Opis avtomobila" cols="15" rows="5" oninput="opisValidacija()">{{ old('opis') }}</textarea>

                            @error('opis')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                            <span class="error">To polje je obvezno</span>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary btn-padding" value="Dodaj">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

code/Avtoservis/resources/views/car/index.blade.php
@extends('layouts.app')

@section('content')


    <div class="title m-b-md">
        Seznam Cars
    </div>
    <a href="/cars/create">Dodaj avtomobil</a>

    <div>
        <table>

            @foreach($cars as $car)
                <tr>
                    <td>{{ $car->znamka }}</td>
                    <td>{{ $car->model }}</td>
                    <td>{{ $car->letnik }}</td>
                    <td>{{ $car->opis }}</td>
                    <td><a href="/cars/{{ $car->id }}">Podrobnosti</a></td>
                    <td><a href="/cars/{{ $car->id }}/edit">Uredi</a></td>
                    <td>
                        <form action="/cars/{{ $car->id }}" method="POST">
                            @csrf
                            @method('DELETE')

                            <button type="submit">Izbriši</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </table>
    </div>

@endsection

code/Avtoservis/resources/views/car/show.blade.php
@extends('layouts.app')

@section('content')

<div class="title m-b-md">
    {{ $car->znamka }} {{ $car->model }}
</div>

<div class="content">
    <ul>
        <li>{{ $car->letnik }}</li>
        <li>{{ $car->opis }}</li>
    </ul>
</div>

@endsection

code/Avtoservis/resources/views/car/update.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="jumbotron text-center login_form shadow-lg p-3 my-5 bg-white">
                    <div class="title m-b-md">
                        Uredi avtomobil
                    </div>
                    <div>
                        <form action="/cars/{{ $car->id_avtomobila }}" method="post">
                            @method('PATCH')
                            @csrf

                            <input type="hidden" name="id_uporabnika" value="{{ auth()->id() }}">
                            <input type="hidden" name="is_active" value="1">

                            {{-- @if($errors->any())
                                <div class="errors">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif --}}

                            <div class="form-group form-znamka">
                                <input type="text" class="form-control @error('znamka') is-invalid @enderror" name="znamka" id="znamka" placeholder="Znamka avtomobila" value="{{ $car->znamka }}" oninput="znamkaValidacija()" autofocus>

                                @error('znamka')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                                <span class="error">To polje je obvezno</span>
                            </div>
                            <div class="form-group form-model">
                                <input type="text" class="form-control @error('model') is-invalid @enderror" name="model" id="model" placeholder="Model avtomobila" value="{{ $car->model }}" oninput="modelValidacija()">

                                @error('model')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                                <span class="error">To polje je obvezno</span>
                            </div>
                            <div class="form-group form-leto_prve_registracije">
                                <input type="number" class="form-control @error('leto_prve_registracije') is-invalid @enderror" name="leto_prve_registracije" id="leto_prve_registracije" placeholder="Leto izdelave" value="{{ $car->leto_prve_registracije }}" oninput="leto_prve_registracijeValidacija()">

                                @error('leto_prve_registracije')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                                <span class="error">To polje je obvezno</span>
                            </div>
                            <div class="form-group form-opis">
                                <textarea name="opis" class="form-control @error('opis') is-invalid @enderror" id="opis" placeholder="Opis avtomobila" cols="15" rows="5" oninput="opisValidacija()">{{ $car->opis }}</textarea>

                                @error('opis')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                                <span class="error">To polje je obvezno</span>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary btn-padding" value="Uredi">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection